### ISSUE TITLE
Utility Viewer - Find Existing Plan - All Users

### ISSUE THREAD

**Issue by amanda-oshea** [JMurk/Utility_Viewer_Issues#100]
The user should have the option to set Plan Created By and Responsible Party back to 'All Users' after they have selected a name from the dropdown.

**Comment by JMurk** [comment]
Actually you can do this by deleting the text in the input box.  Do you think that is too hidden?

**Comment by amanda-oshea** [comment]
I do for the basic user.

**Comment by JMurk** [comment]
Lu please update so 'All Users' is selectable in the drop down.

**Comment by jday3** [comment]
Instead of adding it to the dropdown, I added a button to the right of each dropdown that says 'All', which clears the value. This is on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
