### ISSUE TITLE
Utility Viewer - Report - Add Valve ID

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#102]
Please add the actual Valve ID to the Valve Shutdown Plan Report.  I'm not sure what the current PLAN VALVE ID is, but it does not appear to be useful.  The ID should be something like WHH27__032875V.

![image](https://cloud.githubusercontent.com/assets/5805454/4045841/67c35a9e-2d2d-11e4-9447-4ca132623d66.png)

**Comment by jday3** [comment]
Done on dev/prod. Previously the report wasn't in the production environment but I pushed it down there as well.

**Comment by JMurk** [comment]
Confirmed complete on dev and prod.
