### ISSUE TITLE
Utility Viewer - Scroll Bar Causing Tools to Disappear

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#104]
When pressing the right-hand scroll tool repeatedly, upon the last click the valve tool group disappears completely.

Please adjust this so that the group never disappears.

*\* This is likely not related to the issue Dale Walker is experiencing **

**Comment by kanglu666** [comment]
fixed at city dev, please test

**Comment by alanfoster99** [comment]
Have cleared cache, reloaded -- problem persists on dev.

**Comment by kanglu666** [comment]
fixed for both dev and prod, please test

**Comment by alanfoster99** [comment]
Confirmed and closed
