### ISSUE TITLE
Utility Viewer - Export Leak Surveys to CSV

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#105]
Please add functionality to export Leak Survey data to CSV

**Comment by alanfoster99** [comment]
This has become high priority -- please address.

**Comment by kanglu666** [comment]
export Leak Survey data to CSV function has been done in prod Utility Viewer, please test

**Comment by JMurk** [comment]
Need to make sure that this is implemented in Dev as well.  10.2 dev will soon become production and needs to match all functionality.

**Comment by amanda-oshea** [comment]
Your killing me with the emails

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
From: Joe Murk
Date:09/20/2014 9:58 AM (GMT-06:00)
To: JMurk/Utility_Viewer_Issues
Subject: Re: [Utility_Viewer_Issues] Utility Viewer - Export Leak Surveys to CSV (#105)

Need to make sure that this is implemented in Dev as well. 10.2 dev will soon become production and needs to match all functionality.

**Comment by alanfoster99** [comment]
Confirmed in Prod.  Not working in Dev -- please implement.

**Comment by kanglu666** [comment]
Export Leaks to CSV is working in city dev now.

**Comment by alanfoster99** [comment]
Confirmed and closing
