### ISSUE TITLE
Utility Viewer - C.A. Request - Complete Status for a New Plan

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#106]
Issue:  When creating a new shutdown plan, users cannot select "Complete" as a status.

![image](https://cloud.githubusercontent.com/assets/5805454/4080168/6ca8c250-2edc-11e4-9b51-8f07493304dc.png)

Resolution:  Please allow users to select Complete as a status when creating a plan.  ALSO, when Complete is chosen, please remove the check for when to be executed >= today's date.

**Comment by kanglu666** [comment]
"Complted" status has been added into the plan shut down form.
also check date function has been updated

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated in PROD ready for testing

**Comment by JMurk** [comment]
When trying to save this plan, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5805454/4527456/62f4985c-4d67-11e4-8e0d-fd5b2b535b60.png)

**Comment by kanglu666** [comment]
working on my side.
Please clear browser cache before testing

**Comment by JMurk** [comment]
Enter the following values into the plan information, then attempt to save.  The error then pops up

![image](https://cloud.githubusercontent.com/assets/5805454/4527676/009e7400-4d69-11e4-9aba-d22ccf407d3c.png)

**Comment by JMurk** [comment]
Complete.
