### ISSUE TITLE
Utility Viewer - C.A. Request - Edit Status of an Existing Plan

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#107]
Issue:  Users cannot edit the Status of an existing plan.

Resolution:  Please make Status editable for an existing plan using a drop down.  The drop down should have values of:

-Cancelled
-Completed
-In Progress
-Pending

**Comment by kanglu666** [comment]
plan status field has been added into database, existing plan has the new drop down now, i will make the same updates in valve plan and trace plan

**Comment by kanglu666** [comment]
updated, ready for testing at dev

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated in PROD ready for testing

**Comment by JMurk** [comment]
Confirmed complete.
