### ISSUE TITLE
Utility Viewer - C.A. Request - Add Cancel Tracking Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#108]
Please add fields to the Plan Information of:

-Cancelled Date
-Cancelled Reason

If possible, these fields should only appear when the plan status = "Cancelled."  They should also be required when plan status = "Cancelled."

**Comment by kanglu666** [comment]
new fields have been added into database, how you want to layout these fields in the form of the UV

**Comment by JMurk** [comment]
Add above Survey Date (see that issue) and display only when status = "Cancelled"

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
