### ISSUE TITLE
Utility Viewer -  Measure Tool - Clear Results

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#109]
Issue:  When you click the clear graphics button on the Measurement Information window, the graphics clear from the map view, but the results remain.

Resolution:  Please clear the results when the clear graphic button is clicked.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete on Dev.  Ready for production.

**Comment by kanglu666** [comment]
ready for testing in prod

**Comment by JMurk** [comment]
Confirmed complete.
