### ISSUE TITLE
Utility Viewer - C.A. Request - Display Measurement Dynamically

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#110]
Is it possible to dynamically display the measurement of a line as the user is drawing it?  In other words, as the user is drawing the results are constantly showing the updated measurement.

**Comment by BC89** [comment]
Yes it’s possible.

**Comment by JMurk** [comment]
Lu, please develop as a LOW PRIORITY item.

**Comment by JMurk** [comment]
This has come up as a request once again.  Bumping up to moderate priority.

**Comment by jday3** [comment]
@BC89, how do you propose we do this? The draw toolbar only has a listener for onDrawEnd and onDrawComplete

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to production.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
