### ISSUE TITLE
Utility Viewer - Custom Extent - Zoom Button Hides

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#111]
Issue:  On small screens, the zoom and delete buttons at the bottom of the Existing extent grids are hidden.

![image](https://cloud.githubusercontent.com/assets/5805454/4080597/1a33f892-2ee0-11e4-9753-5c14eb6637aa.png)

Resolution:  Potentially move these buttons to the bottom of the panel (next to the Clear button).

**Comment by kanglu666** [comment]
fixed, please test at city dev

**Comment by JMurk** [comment]
Confirmed complete of Dev. Ready for Production.

**Comment by kanglu666** [comment]
ready for testing in prod

**Comment by JMurk** [comment]
Confirmed complete.
