### ISSUE TITLE
Utility Viewer - C.A. Request - New Plan Type

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#112]
Please add a plan type of "Survey Only"

**Comment by kanglu666** [comment]
plan type "Survey Only"has been added to the existing plan form

**Comment by JMurk** [comment]
Please add this to the list for new plans as well.

**Comment by JMurk** [comment]
This has become high priority, please address ASAP.

**Comment by kanglu666** [comment]
updated, please test

**Comment by JMurk** [comment]
Confirmed complete.
