### ISSUE TITLE
Utility Viewer - C.A. Request - Add Fields to Plan Information

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#113]
Please add the following fields to Plan Information:

-Survey Date (Date)
-Charge No. (Varchar, 50)
-Contractor Name (Varchar, 100)
-Contractor Phone (Varchar, 20)
-Inspector Name (Varchar, 100)
-Inspector Phone (Varchar, 20)

**Comment by kanglu666** [comment]
fields have been added into database.
how you want to layout these fields in the plan information form in Utility Viewer

**Comment by JMurk** [comment]
![image](https://cloud.githubusercontent.com/assets/5805454/4137537/0d2afec8-3388-11e4-9d5e-e3da59dde394.png)

Keep the window the same size, but add vertical scrolling to view additional fields.

**Comment by jday3** [comment]
Done, on dev.

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
