### ISSUE TITLE
Utility Viewer - Discrepancies - Description Character Limit

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#114]
Issue:  If a user enters more than 255 characters in the Detailed Description box and tries to submit, the  progress bar will continuously spin without ever adding the point.

Resolution:  Please add a function to stop the user from entering characters after they get to 255 OR add a warning message when they try to submit a discrepancy with too many detail characters.

**Comment by kanglu666** [comment]
done at city dev, please test

**Comment by JMurk** [comment]
Please update the message to read:  "You have exceeded the maximum amount of allowable characters in your description.  Please limit to less than 256."

**Comment by kanglu666** [comment]
done for both dev and prod, please test

**Comment by JMurk** [comment]
Confirmed complete.
