### ISSUE TITLE
Utility Viewer - Deleting Extents - Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#115]
Please fix the following typo on the delete extent prompt.

![image](https://cloud.githubusercontent.com/assets/5805454/4122022/5aacc9b0-32c0-11e4-9de7-4e4998b3f8bf.png)

it should read "You are" not "Your are"

**Comment by kanglu666** [comment]
updated at city dev, please test

**Comment by JMurk** [comment]
Confirmed complete on Dev.  Ready for Prod.

**Comment by kanglu666** [comment]
ready for testing in prod

**Comment by JMurk** [comment]
Confirmed complete.
