### ISSUE TITLE
Utility Viewer - Saving Extents - Message Typo/Change

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#116]
Please change the following confirmation message

![image](https://cloud.githubusercontent.com/assets/5805454/4136112/d59f105e-337b-11e4-942f-0da69932c5aa.png)

to read:

"The current extent has been saved successfully!"

**Comment by kanglu666** [comment]
updated for both dev and prod

**Comment by JMurk** [comment]
Confirmed complete.
