### ISSUE TITLE
Utility Viewer - Deleting Extents - Message Typo/Changes

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#117]
Please change the following message
![image](https://cloud.githubusercontent.com/assets/5805454/4136144/2614cbc8-337c-11e4-8bdc-31025bc6b9b8.png)

to read:
"The selected extent has been deleted successfully"

Also, change the following message
![image](https://cloud.githubusercontent.com/assets/5805454/4136396/17ec1040-337e-11e4-8781-9fa69849e162.png)

to read:
"You are not authorized to delete this extent!"

**Comment by kanglu666** [comment]
done for both dev and prod, please test

**Comment by JMurk** [comment]
Confirmed complete for both.
