### ISSUE TITLE
Utility Viewer - Network Trace - Update Call

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#118]
Please update per Gerry's instructions:

"for calling the network trace (prod, dev 10 & 10.2), wherever there is a parameter or SOE property value like below …
FEAT_STATUS = 'ACT' AND VALVE_USE IN  (12,2,9,5)

Please change it to:
FEAT_STATUS in('ACT', ‘PAB’, ‘PRM’, ‘PRP’, ’PUP’, ‘PCL’) AND VALVE_USE IN (12,2,9,5)

**Comment by kanglu666** [comment]
dev 10.2 trace service does not need to update.
prod 10.0 does need to update this.
once next push to prod, i will update this.

**Comment by JMurk** [comment]
Ok, please assign back to me when push has been completed.

**Comment by kanglu666** [comment]
trace service has been updated at city PROD, ready for testing

**Comment by JMurk** [comment]
Complete.
