### ISSUE TITLE
Utility Viewer - Deselect Mains - C. A. Request

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#119]
When selecting mains for valve shutdown plan, there is currently no way to deselect a main.  Please add this functionality.

Either create a new tool with button to do this, or allow <CTRL>+<CLICK> to deselect

**Comment by jday3** [comment]
Now, when selecting mains, there is a list of selected mains that allows you to deselect them. This is on dev

**Comment by alanfoster99** [comment]
Looks like it works well, but it exposes an issue:

If the user closes the "Perform Trace" window by clicking the X in the upper right corner, the winder is permanently gone and the page must by reloaded.  Please investigate.

**Comment by jday3** [comment]
What I am seeing is a little different - when I close the window, I have to click the toolbar icon again and do a select on the map and the window then opens again. This is the same on production

**Comment by alanfoster99** [comment]
However, if you deselect mains using this workflow, then try to select additional (previously unselected) mains, the window does not pop up.

**Comment by jday3** [comment]
This should be fixed now - on dev

**Comment by alanfoster99** [comment]
Looks good -- only one last thing:

Please change the popup to read "Remove Main" instead of "Remove Valve"

**Comment by jday3** [comment]
Done. I also added a button to remove all mains because it seemed useful. If you're satisfied, I can push it to production.

**Comment by JMurk** [comment]
This has been functioning on prod for some time now.  Closing.
