### ISSUE TITLE
Utility Viewer - Main Trace - Hydrant Valves

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#12]
Issue:  _As Per Amy's Comment_: "The hydrant valves should be removed from the trace and from the results, they are showing up in the valves that do not need to be operated, but are not needed."

Resolution:  Lu- Please investigate and resolve accordingly.  This may be an issue for Gerry.  If so, please let me know.

**Comment by kanglu666** [comment]
Looks like need work with Gerry

**Comment by JMurk** [comment]
Gerry, please investigate.

**Comment by kanglu666** [comment]
updated from dashboard side. please test

**Comment by JMurk** [comment]
It appears that this has been fixed, I have not been able to duplicate the original issue.
