### ISSUE TITLE
Utility Viewer - Valve Status - Add Access & Problem Dropdowns

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#122]
Please make Valve Access and Valve Problem editable with a dropdown only.  The dropdowns should use the following code AND Description values:

![image](https://cloud.githubusercontent.com/assets/5805454/4326683/e2f1fc1a-3f71-11e4-86c0-1205b0d19e3d.png)

![image](https://cloud.githubusercontent.com/assets/5805454/4326633/6fced208-3f71-11e4-9c7a-8bf3480d83f2.png)

**Comment by kanglu666** [comment]
both fields have been applied with domains code and value. 
please test city dev

**Comment by JMurk** [comment]
Please change "SPIN FREE"  to "SPINS FREE"  then you may push to prod.
![image](https://cloud.githubusercontent.com/assets/5805454/4345532/74616caa-40d3-11e4-879b-e02149328d9a.png)

**Comment by kanglu666** [comment]
updated in PROD, ready for testing

**Comment by JMurk** [comment]
Confirmed complete.
