### ISSUE TITLE
Utility Viewer - Invalid Features - Add Flag on Existing Plan Screen

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#124]
On the Find Existing Plan window, add a column on the right with no title.  In this column, display a red ! for plans that have invalid features.  
![image](https://cloud.githubusercontent.com/assets/5805454/4337076/11db3650-400c-11e4-967b-bd8611f97ad8.png)

If any of the following fields = "Y" in PLANNED_SHUTDOWNS the ! should display. HasInvalidValves, HasInvalidHydrants, HasInvalidMains, HasInvalidMeters, HasInvalidElement

Add a tool tip if possible that says "Plan has Invalid Features!"

**Comment by JMurk** [comment]
Please use the HasInvalidElement field as Gerry pointed out.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
