### ISSUE TITLE
Utility Viewer - Invalid Features - Add Warning Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#125]
When a user opens an existing plan with invalid VALVES or MAINS, display a message that reads:

"WARNING:  The selected plan contains invalid features.  For an accurate shutdown plan, please re-trace."

When the plan has invalid meters or hydrants, no message is required.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev. Please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
