### ISSUE TITLE
Utility Viewer - Invalid Features - Highlight in List

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#126]
When Invalid features are present, they should be shown in the list of features in red font.  You can derive this info from
V_PLAN_MAINS_NOT_IN_WA_MAINS, V_PLAN_HYDRANTS_NOT_IN_WA_HYDRANT, 
V_PLAN_METERS_NOT_IN_WA_METER

![image](https://cloud.githubusercontent.com/assets/5805454/4337577/d74bfd80-4010-11e4-916b-029491936332.png)

Also, if possible, add a string of text along the top that reads "There are invalid features in this list!"

**Comment by jday3** [comment]
I don't think the invalid features are being returned and displayed in the grids.

**Comment by JMurk** [comment]
Ok, that's fine, I think the flag on the first page will suffice.
