### ISSUE TITLE
Utility Viewer - Mobile - Discrepancy Dropdowns Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#127]
**Issue:** When adding a discrepancy in the UV mobile, the dropdown input boxes do not work (they don't present the list of valid values)

![image](https://cloud.githubusercontent.com/assets/5805454/4340883/fa79b974-4032-11e4-87fe-2dfb3989d271.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed, please test

**Comment by JMurk** [comment]
Confirmed in prod, please update on dev as well.

**Comment by kanglu666** [comment]
updated on both dev and prod.

**Comment by JMurk** [comment]
Confirmed complete.
