### ISSUE TITLE
Unable to save Main Shutdown Plans - "date error"

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#128]
Please look into this issue ASAP.  We are unable to save shutdown plans.  A popup window of date error comes up when we try. (Date and time are being filled out)

**Comment by kanglu666** [comment]
working fine at my side. Please give me a screen shot and some details.

**Comment by kanglu666** [comment]
the only one situation you will get the Date Error is: 
when you have when to reversion date and the reverse date < when to executed date. that 's not allowed

**Comment by JMurk** [comment]
Per Alan:
I think it's being caused when the reverse date is the same as the shutdown date
shutdown 10/7/14 @ 10:00
reverse 10/7/14
think it reads the reverse as 10/7/14 00:00

See issue #95 ... that should resolve this issue.

**Comment by kanglu666** [comment]
time picker has been added in the "reserse date" field, please test in dev

**Comment by JMurk** [comment]
Confirmed complete on dev, push to prod.

**Comment by kanglu666** [comment]
updated at PROD, please test

**Comment by JMurk** [comment]
Dave, please confirm and close.

**Comment by JMurk** [comment]
Closing
