### ISSUE TITLE
Error when performing trace analysis

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#129]
At times, the following error is given when trying to perform a trace analysis with the main shutdown tool.

"Tracing web service error occurred with current selected Mains, please report this problem to admin!"

Specifically, Charlie Adcock is trying to perform a trace on the 7 mains in the area of 6700 Holabird Ave as shown in the picture below: 

![6700holabird](https://cloud.githubusercontent.com/assets/7398247/4562252/1db52fa2-4f03-11e4-8ca1-ded5cea0ef61.JPG)

**Comment by JMurk** [comment]
Gerry has determined that there is an issue with the process for long mains.  He is adjusting the code now.

**Comment by JMurk** [comment]
Lu says the issue has now been resolved.  I traced in that area and it worked.  Please test, confirm and close the issue.
