### ISSUE TITLE
Turn on fields in Active Sewer Mains

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#130]
Please turn on the following fields in the Active Sewer Mains

FROM_MANHOLE_ID
TO_MANHOLE_ID

Thank you.
-DT

**Comment by JMurk** [comment]
Updated in both dev & prod.  Please test and confirm both.

**Comment by DaveThomKCI** [comment]
Tested.  Looks good.  Thanks.
