### ISSUE TITLE
Valve condition layer needed in UView

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#132]
User states valve condition layer was in UView but now is not.  I've searched around and it seems like what he is referring to is the layer called "Valve Condition" in the Water Operations group which is not available in the UView view.  I suggest we either add Water Operations group to UView or give more users access to WAView.

Specifically, if we are just adding users to WAView, please add raye.woodley and jamesw.johnson

**Comment by JMurk** [comment]
Both users have been added to WAView.

**Comment by JMurk** [comment]
This has been completed and is being closed.
