### ISSUE TITLE
Utility Viewer - Shutdown Plans - Actual Start & Date Completed Format

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#133]
Please update the Actual Start Date and Date Completed to the Date & Time format.

![image](https://cloud.githubusercontent.com/assets/5805454/4645872/12502a16-546e-11e4-82eb-2038d24bdb20.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
