### ISSUE TITLE
Utility Viewer - Time Picker Change

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#134]
Please change the format of the time picker from 24-hours, minutes, and seconds to 12-hours, minutes with AM/PM.  Example:  10:35 AM

**Comment by JMurk** [comment]
These controls appear to be on the Main Shutdown Plan Information forms:

![image](https://cloud.githubusercontent.com/assets/5805454/7431793/1f8ef45a-eff0-11e4-8c5c-7f80e8a6f987.png)

**Comment by jday3** [comment]
The date time picker is a custom component and would require a pretty decent sized effort to make the format change. I'm not sure that it is worth it

**Comment by JMurk** [comment]
ok, we will keep this as-is
