### ISSUE TITLE
Utility Viewer - Update Status - New Valve

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#135]
For valves without an existing status in history, updates cannot be made within Utility Viewer.  Please correct this issue to allow this.

**Comment by jday3** [comment]
You can now update the status of a valve with no status history. This is in dev. When you select the valve in the valve status window and it has no history, it will alert you that no status history exists, but you can then make the first status update. Here are some Valve Ids of valves that have no status records for you to search on (in dev):

WY26___071094V
WY26___071093V
WY26___071092V
WY26___071091V

**Comment by alanfoster99** [comment]
Seems to work, but won't accept inspection results unless I populate the exercise tab -- even if I put in "Not Exercised" I have to populate the rest w/ 0's.  Is this default?

**Comment by JMurk** [comment]
I'm not sure of what the original design was.  Do you think it should be changed?

**Comment by alanfoster99** [comment]
I think it should, yes

**Comment by jday3** [comment]
I was able to save a valve status by only populating the POSITION FOUND and CONDITION dropdowns and by leaving the EXERCISED dropdown empty. Is this what you are experiencing?

**Comment by alanfoster99** [comment]
Jesse, what you outline seems to be working for me now, too.  Please go ahead and push to prod.

**Comment by jday3** [comment]
done

**Comment by alanfoster99** [comment]
Closing
