### ISSUE TITLE
Utility Viewer - Main Shutdown Plan Evaluation - Created by Auto Populating

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Utility_Viewer_Issues#137]
On creation of a new Main Shutdown Plan the 'Created by' field should be autopopulated with the current user's name.  This is not happening.  
![missingcreatedby](https://cloud.githubusercontent.com/assets/5039052/4667481/6a61a6fe-555d-11e4-8544-e04756bafa0c.GIF)

**Comment by kanglu666** [comment]
working for me.

**Comment by JMurk** [comment]
Appears to be fine, closing.
