### ISSUE TITLE
Utility Viewer: Trace/retrace error

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Utility_Viewer_Issues#138]
When performing a trace analysis, get the error below.  Tried with several different mains.
![traceerror](https://cloud.githubusercontent.com/assets/5039052/4667904/fcd20314-5560-11e4-8f38-1aa569f5dacf.GIF)

Tried to do a retrace after an earlier successful trace and get the error below:
![retraceerror](https://cloud.githubusercontent.com/assets/5039052/4667914/0e91eb00-5561-11e4-98ac-774442e03e2f.GIF)

**Comment by JMurk** [comment]
Per Gerry, this is a known dev issue.  Closing.
