### ISSUE TITLE
Utility Viewer Mobile - Discrepancies - REPORTED_BY Not Popualting

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#139]
**Issue**:  When creating a discrepancy from a mobile application, the REPORTED_BY field is not auto-populated.

**Resolution**:  Please update so that it is auto-populated with the user's login name.

**Comment by kanglu666** [comment]
it's working fine

**Comment by JMurk** [comment]
Nope.  Not working from mobile UV.

![image](https://cloud.githubusercontent.com/assets/5805454/5143045/5ad1c33c-7159-11e4-9417-65caa349c80d.png)

**Comment by kanglu666** [comment]
should be fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
