### ISSUE TITLE
Utility Viewer - Discrepancies - Date Logged Off

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#140]
**Issue**: The date/time that is autopopulated in the Date Logged field is off by a few hours.

**Resolution**: I suspect the server is set to GMT.  If that is indeed the case, please update to eastern standard time.

**Comment by kanglu666** [comment]
trigger updated, it's using the right date time, please test

**Comment by JMurk** [comment]
Confirmed complete.
