### ISSUE TITLE
Utility Viewer - Discrepancies - Add Notification

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#141]
Please add a notification that reads:

"You have exceeded the maximum amount of allowable character in your source.  Please limit to less than 50."

when the user enters too many characters in the source field.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
The length has been updated to 255 on dev.  Please also include the message, but change 50 to 255 in the message text.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
I had a typo above that made it's way to the message.  Please change "character" to "characters" and push to prod.  The field length is updated there.

![image](https://cloud.githubusercontent.com/assets/5805454/5704966/c90c5ce6-9a43-11e4-9d73-f19c55743e78.png)

**Comment by jday3** [comment]
fixed

**Comment by JMurk** [comment]
Now the dropdowns are not working... 

![image](https://cloud.githubusercontent.com/assets/5805454/5741524/89a2c0d0-9bd9-11e4-9a89-cbebff206f60.png)

**Comment by jday3** [comment]
The api is using the old discrepancy domain tables. Will update

**Comment by jday3** [comment]
Fixed - and now the source check/text should be on production also

**Comment by JMurk** [comment]
Confirmed complete.
