### ISSUE TITLE
Utility Viewer - Issues Changing User's Default View

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#142]
Please change the default view for Diego.Calderon to be WWView

**Comment by DaveThomKCI** [comment]
We have tried to change this view several times in different environments and it still fails.  Tried with Firefox, Chrome, and Chrome incognito.  The save function did work for me.

**Comment by alanfoster99** [comment]
See if he is allowed to right cookies, or if he is accepting them, or if there is a temp folder that his user has permissions for; seems more like a browser issue to me.

**Comment by JMurk** [comment]
Has this issue been resolved on the user's side?  If so, what was the issue?

**Comment by DaveThomKCI** [comment]
The save box is still not working. We tried saving the WWView as the default view in firefox, chrome, and IE and it did not work.  We also cleared the cache and cookies in firefox, but that was not useful either.  

We also tried the process, with his log in, on my machine (incognito chrome).  Still no luck.  In the exact same environment, I logged in, saved, and it worked.

**Comment by jday3** [comment]
This should be working now

**Comment by JMurk** [comment]
Confirmed complete.
