### ISSUE TITLE
Utility Viewer - Add Water Features - Zoom In Message Typos

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#143]
**Issue:**  There are a few typos in the following warning message.

![image](https://cloud.githubusercontent.com/assets/5805454/5361241/06253966-7f98-11e4-834b-96a5e1cd460f.png)

**Resolution:** Please make sure the message reads:

"Warning: Cannot create point.  Please zoom into a scale larger than 1:100 and try again."

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
