### ISSUE TITLE
Utility Viewer - Add Water Features - Hydrants Snapping

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#144]
**Issue:**  When Attempting to add a new hydrant feature, the system checks to see if the user's click is within a short distance of a main.  This should not occur for hydrants as the connector main segment  likely does not exist.

**Resolution:** Please remove this check for Hydrants.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
