### ISSUE TITLE
Utility Viewer - Add Water Features - Valve Missing Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#145]
**Issue:** There are a few fields that are missing from the Valve attributes form when adding a new valve.  

![image](https://cloud.githubusercontent.com/assets/5805454/5363156/9d5718b8-7fa7-11e4-9c15-77e5f83af268.png)

**Resolution:** Please add the following fields:
1. MANUF_CD (Manufacturer), domained dropdown, place after valve use
2. DATE_OPERATED (Date Operated), date/time calendar control, place after install date
3. CONDITION (Condition), domained dropdown, place after date operated

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
