### ISSUE TITLE
Utility Viewer - Add Water Features - Incorrect Attribute Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#146]
**Issue:**  On the Hydrant attribute form, the first field is labeled "Valve Use"  (was a carry over from the valve form).

![image](https://cloud.githubusercontent.com/assets/5805454/5363264/93c43b04-7fa8-11e4-968f-8e6aa781d6e9.png)

**Resolution:** Please update the label to read "Manufacturer"

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
