### ISSUE TITLE
Utility Viewer - Add Water Features - Hydrant Missing Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#147]
**Issue:** There are a few fields that are missing from the Hydrant attributes form when adding a new Hydrant feature.  

![image](https://cloud.githubusercontent.com/assets/5805454/5363835/fe8c044a-7fac-11e4-9a0e-e4e3fd0c710d.png)

**Resolution:** Please add the following fields:
1. RESP_AGENCY (Responsible Agency), domained dropdown, place after Lock Model
2. FAB_DATE (Fabrication Date), date calendar control, place after Responsible Agency
3. INSTALL_DATE (Install Date), date calendar control, place after Fabrication Date
4. OPER_DATE (Date Operated), date/time calendar control, place after Install Date
5. EDIT_COMMENT (Comments), free form text, place at the bottom.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
