### ISSUE TITLE
Utility Viewer - Add Water Features - Autopopulate Fields (Basic)

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#148]
**Issue:**  A few fields identified to be auto-populated are not doing so.

**Resolution:**  Please set the following fields to be auto-populated for both Hydrants and Valves with the corresponding values:
1. EDIT_DATE - current date
2. BFD_FIELDCHECK_DATE - current date
3. BFD_FIELDCHECK_STATUS - 2

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev.  Closing now since function not in prod yet.
