### ISSUE TITLE
Utility Viewer - DOT Snow - Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#149]
**Issue:**  There is a typo in the feed name for DOT Snow.  It says "Show" instead of "Snow".  This is in dev only.

![image](https://cloud.githubusercontent.com/assets/5805454/5569176/bd5c915a-8f39-11e4-83a5-c3247aafd018.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
