### ISSUE TITLE
Utility Viewer - User Guides - Links Broken

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#150]
**Issue:**  The links in the Information toolbar to the User Guides are broken.  I believe this is because they were stored on dpw-gw03-srv, which has been decommissioned.

**Resolution:**  Can you point to the user guides stored here: \dpw-gis102-prd\web_data\User Guides

**Comment by jday3** [comment]
There isn't an IIS entry pointing to that folder so for now I'm just pointing to the user guides in the portal application.

**Comment by JMurk** [comment]
OK, they are loading fine, so that works.  Closing.
