### ISSUE TITLE
Utility Viewer - Map Update - Add DPW AVL Layer

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#153]
Add the AVL layer with a subset of DPW only vehicles to a group in the WAVIEW, WWVIEW, SWVIEW

**Comment by JMurk** [comment]
I have created a new service called "AVL" on both prod and dev.  Please create a new feed in the Utility Viewer:

-Place above Work Order feeds
-Leave off by Default
-Make available in WAVIEW, WWVIEW, and SWVIEW

**Comment by kanglu666** [comment]
layer AVL has been added into both PROD and DEV, please test

**Comment by JMurk** [comment]
Confirmed complete.
