### ISSUE TITLE
Utility Viewer - Add Water Features - Valve Use

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#154]
**Issue:**  The default value for the VALVE_USE field is saved regardless of what the user chooses when adding the valve through the Utility Viewer.  Prod & Dev.

**Resolution:** Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
