### ISSUE TITLE
Utility Viewer - Add Water Features - Capture Method Autopopulate

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#155]
Please update the autopopulate of the CAPTURE_METHOD field to "UV"

**Comment by jday3** [comment]
Done on dev

**Comment by jday3** [comment]
Scratch that. "UV" needs to be added to the domain. It won't let me add new features when I pass in "UV" for CAPTURE_METHOD

**Comment by JMurk** [comment]
It should be in place in the dev database now.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Appears to have been pushed to prod. as well. Closing.
