### ISSUE TITLE
Utility Viewer - Add Water Features - Time

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#156]
**Issue:**  For all date/time fields captured in hydrants and valves, the time is off from EST.

**Resolution:**  Probably using GMT so needs to be converted to EST.  Please also remove the time portions for install date and fabrication date as the are not needed (date only).

**Comment by jday3** [comment]
Can you show me where you are seeing a discrepancy? The values that are being sent to the server are EST as shown below (Added valve at 8:17)
![valve](https://cloud.githubusercontent.com/assets/4439618/5875196/865231d0-a2d8-11e4-9669-65b426d1cf29.PNG)

I removed the time component of install/barication date on both hydrants and valves.

**Comment by JMurk** [comment]
This may be just happening on prod and not dev.

**Comment by JMurk** [comment]
This is still occurring on prod.  In the example below, I created the point at about 11:15AM.

![image](https://cloud.githubusercontent.com/assets/5805454/7432413/e93e779e-eff5-11e4-8970-4214be9d5912.png)

**Comment by jday3** [comment]
Fixed on dev/prod

**Comment by JMurk** [comment]
Still off in prod.

**Comment by jday3** [comment]
should be fixed now

**Comment by JMurk** [comment]
Confirmed complete.
