### ISSUE TITLE
Utility Viewer - Add Water Features - Date Inputs

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#157]
**Issue:**  The user is currently allowed to still submit a feature if a date field is malformed (letters, special characters, too many slashes, etc.).  When viewed in ArcMap, these features have null values for fields that were entered malformed in the Utility Viewer.  This should not be allowed.
![image](https://cloud.githubusercontent.com/assets/5805454/5838623/bb093c44-a156-11e4-8ecd-1503104e1b71.png)

**Resolution:**  Do not allow manual entry into those boxes.  Dates must be choosen via the calendar control.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
