### ISSUE TITLE
Utility Viewer - Add Water Features - Security

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#159]
Please be sure that this tool ties into the security of the trace functionality.  It should only be visible to users with permissions of "Supervisor" for Main Tracing.

**Comment by kanglu666** [comment]
add water features functions has been configured with the security of the trace functionality. please test on dev.

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by JMurk** [comment]
Complete on prod.
