### ISSUE TITLE
Utility Viewer - Valves Toolbar - Change Name

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#160]
Please change the heading on the "Valves Toolbar" to "Water Tools"

![image](https://cloud.githubusercontent.com/assets/5805454/5839674/c3739738-a15d-11e4-9b24-874a7635cf1f.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
