### ISSUE TITLE
Utility Viewer - Manhole GIS Locator not functioning 

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#161]
I believe this used to be one of the layers you could search by attribute using the GIS locator.  I have a user telling me he has always searched that way and now it reads "No Searchable Attribute"

**Comment by JMurk** [comment]
This is because layer names in the feed have changed.  
![image](https://cloud.githubusercontent.com/assets/5805454/6414939/524d87ac-be69-11e4-97a0-2d89511c34b1.png)

see UV for the rest.

**Comment by jday3** [comment]
Fixed

**Comment by JMurk** [comment]
This still does not appear to be working for me.

**Comment by jday3** [comment]
Sorry, needed to update the web service as well. Should be working now.

**Comment by JMurk** [comment]
Confirmed complete.
