### ISSUE TITLE
Utility Viewer - WW View - Feature Information/Identify

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#162]
**Issues:**  When you switch to WWView, the feature information tab appears in the top left hand corner with nothing populated.

![image](https://cloud.githubusercontent.com/assets/5805454/6470146/8f779c82-c1af-11e4-82f4-44bba77da658.png)

Also, there are no layers set as selectable by default.

**Comment by jday3** [comment]
Fixed. Bug was due to updated layer names not updated in the wwviewconfig file

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
This has happened again.  Updates were made to the Base Map service.  Please update ASAP.

**Comment by JMurk** [comment]
Bug is only occurring in the production environment.

**Comment by taojun545** [comment]
Fixed on prod. Updated three config xml files:
wwviewconfig.xml
uviewconfig.xml
swviewconfig.xml

**Comment by JMurk** [comment]
Looks good. Confirmed complete.
