### ISSUE TITLE
Utility Viewer - Main Shutdown Plan Type - Customer List 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#163]
Please add a shutdown plan type of "Customer List"

**Comment by jday3** [comment]
Done on dev and prod

**Comment by JMurk** [comment]
Please add it to the Plan type dropdown when editing existing plans.

![image](https://cloud.githubusercontent.com/assets/5805454/6620404/eb8ea06c-c8a6-11e4-8f6c-2d357102dae3.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
