### ISSUE TITLE
Utility Viewer - Customer List Plan - Expand WO Types

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#164]
For the Work Order ID dropdown, please expand the filter to include the following WO types:

![image](https://cloud.githubusercontent.com/assets/5805454/6869539/52eb9664-d46b-11e4-8c42-faf43d8afe51.png)

**Comment by jday3** [comment]
Done. dev/prod

**Comment by JMurk** [comment]
Confirmed complete.
