### ISSUE TITLE
Utility Viewer - Active Legend - Broken for WW View

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#165]
The changes to the Wastewater service have broken the Active Legend when that feed is turned on.  Please update.

**Comment by jday3** [comment]
The '(' and ')' characters in some of the layer names pose an issue because the legend uses those characters to split up the different services. It works now, but the layers will have the parentheses removed, so "Sewer Manholes (Active)" shows up as "Sewer Manholes Active"

**Comment by JMurk** [comment]
Confirmed complete.
