### ISSUE TITLE
Utility Viewer - Main Shutdown - Mains stay selected after shutdown saved and closed

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#166]
When a main shutdown is saved and closed, the mains used for that analysis are kept active in the main shutdown dialog when another shutdown is run.  Here are steps to replicate:

Search Active Water Mains for WZ12___0148929M and Zoom In on feature
Select this main using Select Mains Tool
Perform Trace Analysis
Save Plan Information as type Scenario
Close Main Shutdown Plan Evaluation window
Clear All Tracing Graphics
Clear Search Results from GIS Locator Window
at this time, nothing is visibly selected
Search Active Water Mains for WDD08__0150929M and Zoom In on feature
Select this main using Select Mains Tool
You will notice that WZ12___0148929M, the first main selected, is still active in the dialog

Solution:
After a shutdown plan is saved and closed, selected segments should not be retained.  Either use "Clear All Tracing Graphics" to remove the selection, or accomplish programatically when plan is saved and closed.

**Comment by jday3** [comment]
Done on dev/prod. The mains are removed from the perform trace dialog when the user either clears the tracing graphics, or the select mains button.

**Comment by alanfoster99** [comment]
This won't work -- user needs to use select mains button during large-area analysis in order to do the following:

Select mains
Choose to select additional mains
Pan the map
User now needs to press button to select mains again, and first selection(s) need to stay active

**Comment by alanfoster99** [comment]
Solution:
Please leave the functionality such that when the user clears the tracing graphics the mains are cleared from analysis

**Comment by jday3** [comment]
Done on dev/prod

**Comment by alanfoster99** [comment]
Confirmed and closing
