### ISSUE TITLE
Utility Viewer - Main Shutdown - Affected Meter Count Inaccurate in County

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#167]
When a main shutdown in the City is saved and closed, subsequent County main shutdowns (where meters affected is zero) are not updated with the proper value; instead, they retain the City value. Here are steps to replicate:

Search Active Water Mains for WEE18__0037380M and Zoom In on feature
Select this main using Select Mains Tool
Perform Trace Analysis
Number of meters affected is shown as 89 under Plan Information tab
Close Main Shutdown Plan Evaluation window
Search Active Water Mains for WDD08__0150929M and Zoom In on feature
Select this main using Select Mains Tool
You will notice that number of meters affected is 89, same as WEE18__0037380M, the first main selected, despite there being zero meters affected by this second shutdown.

The network trace portion seems to be functioning properly, as the values for affected meters are shown correctly when a plan is saved and re-opened.  The issue only seems to be on initial population of the table.

Solution:
When zero meters (or other feature types) are encountered, retain this value for the display.

**Comment by jday3** [comment]
Fixed on dev/prod

**Comment by alanfoster99** [comment]
Confirmed and closing
