### ISSUE TITLE
Utility Viewer - Customer List Plan - Fields Missing for Existing Plans

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#168]
**Issue:**  When opening an existing plan of type "Customer List," there is no Work Order ID field on the form.

![image](https://cloud.githubusercontent.com/assets/5805454/7031518/272ac43c-dd3a-11e4-8ffa-7f49f7f3946d.png)

**Resolution:** Please add the Work Order ID field to the list.

**Comment by JMurk** [comment]
I don't see any changes in dev or prod.  Please check.

**Comment by jday3** [comment]
Fixed in dev

**Comment by JMurk** [comment]
That looks good.  I think another issue is if the Plan Type is changed from something to Customer List.  Can we make the field appear then?

**Comment by jday3** [comment]
That is fixed now also, on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
