### ISSUE TITLE
Utility Viewer - Find Existing Plan - Created Date Sorting

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#169]
Issue:  Sorting on the Created Date column does not sort in the correct order.  It appears that the field maybe storing as a text value?

![image](https://cloud.githubusercontent.com/assets/5805454/7431236/a3366956-efea-11e4-979d-34db22a4c839.png)

Resolution:  Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Fixed on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
