### ISSUE TITLE
Utility Viewer - Create New Plan - Expose All Fields & Allow Multiple Edits

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#170]
**Issue:**  When creating a new shutdown plan, a number of fields are not able to be populated.  This should not be the case (should be the same form as an existing plan).  

Further, after the initial save, no edits can be made on the plan information window.  The save button becomes grayed out.

![image](https://cloud.githubusercontent.com/assets/5805454/7433006/09e2d53a-effb-11e4-9b7b-013615f2cb01.png)

**Resolution:**  Please add all fields from the Existing Plan information form in the initial create plan plan information form.

Also, allow continuous editing of plan information while on the create plan screen.  Do not disable the save button.

**Comment by jday3** [comment]
Done on dev. The one difference between the two forms is that the initial plan info form doesn't have the 'Cancelled' status and the corresponding date/reason fields

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
