### ISSUE TITLE
Utility Viewer - Plan Information - Add Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#171]
It is being requested that we add fields in the Plan Information table for Foreman Name and Foreman Phone.  On the form, these field should go after Contractor Phone but before Inspector Name.

![image](https://cloud.githubusercontent.com/assets/5805454/7433088/e1ffbcd0-effb-11e4-9f64-49b960372911.png)

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
