### ISSUE TITLE
Utility Viewer - Mobile - Remove Emergency Ops Layer

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#172]
Please remove the "DPW Emergency Operations" feed from the mobile utility viewer (no longer needed).

![image](https://cloud.githubusercontent.com/assets/5805454/7569663/4214fc8c-f7d8-11e4-98d0-e11eef34d98f.png)

**Comment by jday3** [comment]
done on prod

**Comment by JMurk** [comment]
Confirmed complete.
