### ISSUE TITLE
Utility Viewer - Shutdown Plans - Remove Reversal Plans

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#173]
We need to remove the reversal plans from the Utility Viewer. Currently on insert, when the "When to Reverse Operations:" field is populated, a separate but related reversal plan is automatically created.  This along with the reversal plan fields (Is Reverse Plan, Has Reverse Plan) are no longer needed.

![image](https://cloud.githubusercontent.com/assets/5805454/7588235/c2837d9c-f889-11e4-943c-eb38434b00d9.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
