### ISSUE TITLE
Utility Viewer - Find Existing Plan - Result Columns

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#174]
The current field displayed in the Find Existing Plan search results (Plan Name, Description, Created Date) are not has useful as they could be.

![image](https://cloud.githubusercontent.com/assets/5805454/7657440/d8456d98-faff-11e4-85c5-619e3203d7ed.png)

I would like to display the following instead:
-Plan Name
-Plan Type
-Status
-Date to be Implemented

We may have to made the window a bit wider to fit the additional columns.

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
on prod

**Comment by JMurk** [comment]
Confirmed complete.
