### ISSUE TITLE
Utility Viewer - Printing - Stuck on Loading, will not produce print

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#175]
**Issue:**  in production, the export to PDF function gets stuck on the export loading and fails to ever produce a report.

![image](https://cloud.githubusercontent.com/assets/5805454/8036603/e3a08cac-0dc6-11e5-8c27-baadbac744df.png)

**Resolution:**  Please investigate and resolve accordingly

**Comment by jday3** [comment]
Works for me

![image](https://cloud.githubusercontent.com/assets/4439618/8041105/e8cd4e96-0de3-11e5-9022-846f484e75db.png)

**Comment by JMurk** [comment]
No longer an issue.
