### ISSUE TITLE
Utility Viewer - Valve Status Update - Start as Blank Form

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#177]
Users have requested that for a Valve Status update, the form should begin as completely blank.  Users will need to populate the following required fields:

-Position Found
-Position Left
-Turn Positions Change (Auto-Populate Date)
-Condition (Auto-Populate Date)
-Exercised (Auto-Populate Date)
-Turns Exercised

Make sure all date fields are auto-populated when their corresponding features are populated.

When a required field is missing, prompt a message saying "WARNING: Unable to update valve status, required fields are missing!"  If possible, also red line those fields that are missing on the form.

**Comment by jday3** [comment]
Done on dev.

**Comment by jday3** [comment]
These updates have also been made to the mobile valve status application

**Comment by JMurk** [comment]
Looks good, please push to production.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
