### ISSUE TITLE
Legend seems messed up for WWView/Consent Decree

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#179]
In the Consent Decree category, there seems to be legend symbols for nothing at all (no folders are expanded and still symbology is shown.  
![image](https://cloud.githubusercontent.com/assets/7398247/8479848/55428042-20a8-11e5-8f73-21c0a84da38b.png)

Then, if you expand the design project consultant areas layer, it shows symbology that does not match a. what it should be, b. what shows up on the map.  

I believe also that Manhole Ratings, Sewer Structural Rating, and Sewer O and M Ratings are not correct.

**Comment by JMurk** [comment]
This is because some of the data links are broken.  Marian may have moved some data around.  Can you track down the correct data sources for the following layers:

![image](https://cloud.githubusercontent.com/assets/5805454/8480116/f7e3f938-20a9-11e5-935e-089b6f469173.png)

**Comment by DaveThomKCI** [comment]
I actually just ran across this data yesterday... These are tables though - not sure if thats how there were in there before or not...

Instance: dpw-sql-srv
Database: uview
Tables: UVIEW.UVIEW.P8_Manholes, UVIEW.UVIEW.P8_Sewer, UVIEW.UVIEW.SmokeTestedSewer

**Comment by JMurk** [comment]
This has been fixed.
