### ISSUE TITLE
Utility Viewer - Results Window Scroll Bar Issue (IE)

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#180]
When selecting a large amount of items for identification, the scroll bar does not properly size for the results, and the scroll wheel must be used to access all values.  This is visible in IE.

![image](https://cloud.githubusercontent.com/assets/7118831/8549815/d966a57e-249a-11e5-8521-cb91714f5a53.png)

**Comment by jday3** [comment]
Do you know what version of IE? I was unable to replicate this in IE 7 or 10

**Comment by alanfoster99** [comment]
Turns out this only occurs when the display is zoomed in; not sure if bug or IE issue

**Comment by JMurk** [comment]
Closing for now as it appears this was just a browser-specific issue.
