### ISSUE TITLE
Utility Viewer - Scenario Plans - Removed Required Date Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#181]
When the Plan Type = "Scenario"
![image](https://cloud.githubusercontent.com/assets/5805454/9305671/2bf7faf4-44c1-11e5-9202-60c93d89664d.png)

Please remove the requirement for all date fields (all pictured below).  Also be sure that this change is made in the mobile app as well.

![image](https://cloud.githubusercontent.com/assets/5805454/9305658/107d1c00-44c1-11e5-9f23-d5c5c8812a96.png)

**Comment by jday3** [comment]
Done on dev/prod

**Comment by JMurk** [comment]
Confirmed complete in dev/prod desktop & mobile
