### ISSUE TITLE
Utility Viewer - Add New Valve - Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#182]
**Issue:**  Typo in error message:

![image](https://cloud.githubusercontent.com/assets/5805454/9887279/c9491362-5bbc-11e5-85da-bee7de75a485.png)

should be "a new"

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to production

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
