### ISSUE TITLE
Utility Viewer - Field formatting 

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#183]
When inputting the Charge No.  for the AMI project, the field in Utility Viewer is converting the number and it does not allow for hyphens. In addition, It does not allow for hyphens in the Contractor Phone, Foreman Phone, or Inspector Phone fields either.   

Please allow for hyphens, and do not convert the charge number to scientific notation.

![image](https://cloud.githubusercontent.com/assets/7118831/10312616/eeb2829c-6c19-11e5-84cb-026934a26bf6.png)

**Comment by JMurk** [comment]
Joe to check database for data types... should be text.

**Comment by taojun545** [comment]
Change following fields from "NumberField" to "TextField":
Charge No., Contractor Phone, Foreman Phone, Inspector Phone

Joe need to check the database to see the data types of those fields.

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for prod.  All of the mentioned fields are varchar in both dev and prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
