### ISSUE TITLE
Under construction water mains - not showing up dashed

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#185]
Should these be dashed too?  Or at least something different than the active mains?

Charles Adcock was having trouble running main trace tool... Turns out he was selecting under construction mains - he was not aware because they are symbolized the same way.

**Comment by JMurk** [comment]
Should these mains be under "Proposed Water Mains" or in their own layer.  Please advise.

**Comment by DaveThomKCI** [comment]
As long as the symbology is not getting out of control, it should be a separate layer.  Maybe same pattern as the proposed, only brown in color?

**Comment by JMurk** [comment]
This has been updated in dev and prod.
