### ISSUE TITLE
Utility Viewer - Main Shutdown - New types

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#186]
Please add type for "Open Valves Only"; this will occur when no previous shutdown exists, but a main needs to be brought up.

**Comment by taojun545** [comment]
Added new Plan Type into the forms on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to production.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete
