### ISSUE TITLE
Utility Viewer - Shutdown Plan - Remap Work Order ID Field

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#187]
As a result of the Cityworks migration, the Work Order ID field needs to be remapped to the new database.

![image](https://cloud.githubusercontent.com/assets/5805454/10823880/1b0b3970-7e34-11e5-97b1-bdca8f810b01.png)

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete in dev, can be pushed to prod.  Please check the Customer List report.  I created a scenario in dev that should be included in the Customer List report, but the download is blank.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
