### ISSUE TITLE
Utility Viewer - GIS Locator - Not Working for Wastewater Features

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#189]
**Issue:** The GIS locator tool is not working for Wastewater features.  This is occurring in both test and production environments.

![image](https://cloud.githubusercontent.com/assets/5805454/11821110/fb8c3960-a335-11e5-937f-3a549a1e050d.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by jday3** [comment]
The database that is being queried is 169.156.54.44/CityWorks

I checked and the database is offline. Should it be using another database after the migration?

**Comment by JMurk** [comment]
Wow, that is a really old database.  It should be wastewater or publish (either would work) on dpw-sql-srv.

**Comment by jday3** [comment]
alright it is pointing to wastewater now

**Comment by JMurk** [comment]
Confirmed complete.
