### ISSUE TITLE
Utility Viewer - Work Order Layers - Expand to Other Views

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#190]
**Issue:**  Currently there are 4 Work Order feeds in the Utility Viewer (Surface Repair, Storm, Water, Sewer) and they are made available only in their corresponding view (WAView, WWView, ect).  

**Resolution:** Stakeholders are requesting that they all be made available in the following views:
<li>WAView</li>
<li>WWView</li>
<li>SWView</li>

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
