### ISSUE TITLE
Utility Viewer Mobile - Add Work Order Feeds

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#191]
Please add the four Work Order map services/feeds to the mobile Utility Viewer.  They should be off by default and are as follows:

-Surface Repair Work Orders
-Water Work Orders
-Sewer Work Orders
-Storm Work Orders

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
