### ISSUE TITLE
Utility Viewer - New Identify Functionality

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#192]
In the development Utility Viewer we have added a tool to the utilities toolbar for “identify settings.”  This brings up the old layer selection box where users can choose what is selectable.  AS before, default selectable layers are set for each view.  Further, the identify tool is defaulted to select all visible features until the user selects otherwise in the settings.

This needs to be pushed to production.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
