### ISSUE TITLE
Utility Viewer - Another Change to Identify Tool

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#193]
As per Wastewater meeting on 11/14/16, Amy asked that the identify tool that IDs all visible features NOT identify basemap features.  If a user really needed to ID a basemap feature, they would have to use the newly added "old" identify tool - where the user can select the layer to identify.

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
Can you please update this to include "City Street Centerline" from the BaseMap service?

**Comment by taojun545** [comment]
@JMurk "City Street Centerline" doesn't exist in dev BaseMap service, could you update it?

**Comment by taojun545** [comment]
Updated in both dev and prod. But we need update the BaseMap in dev to include "City Street Centerline"

**Comment by JMurk** [comment]
The dev map service has been updated to include the City and County Street Centerline layers.
