### ISSUE TITLE
Search not functional on Sewer Mains

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#195]
GIS Feature search is not autopopulating the dropdown, not returning any results.

![image](https://cloud.githubusercontent.com/assets/7118831/13927073/8233bf4e-ef65-11e5-9cd6-b7ddf0c7ff3e.png)

**Comment by JMurk** [comment]
Appears to be occuring for Wastewater features.

**Comment by taojun545** [comment]
There are many locator queries still using wrong databases, and I will update the setting asap.

**Comment by taojun545** [comment]
Updated "locatorsewerRDBMS" (WasteWater)  and  "locatorstormRDBMS" (sw) on dev.

**Comment by alanfoster99** [comment]
Looks good, thanks.  Please push to Prod.

**Comment by taojun545** [comment]
Updated on Prod.

Joe, there are many differences on "WasteWater" between dev and prod. You may need to sync.
