### ISSUE TITLE
Utility Viewer - Symbology

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#196]
Please add a "D" to the middle of the symbol for division valve.  Bob Suri uses this information frequently, but is color blind and cannot differentiate the red color.

**Comment by JMurk** [comment]
Updated on dev.  Please have Bob verify the contrast is suitable before push to production:

![image](https://cloud.githubusercontent.com/assets/5805454/14210119/928ac660-f7f5-11e5-808a-381980f20aef.png)

**Comment by alanfoster99** [comment]
Verified and ready to go.  Please push to prod.

**Comment by JMurk** [comment]
Done in prod.

**Comment by alanfoster99** [comment]
Confirmed and closing.
