### ISSUE TITLE
Utility Viewer - Address Geocoder - Not Zooming (Dev Only)

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#197]
**Issue:**  In the dev version of the Utility Viewer, the Address Geocoder will return results of a search, but will not zoom to any of the selected results in the map.

**Reproduce**:  
- Expand the Geocoder panel
- Enter "2331 n fulton ave" in the address box
- Click the magnifying glass button
- Select the result from the grid below
- Click the lighting bolt button to zoom

**Comment by taojun545** [comment]
Fixed on dev.

The issue is dev still using DPW-GIS102-SRV 169.156.64.146 (DECOMMISSIONED).

**Comment by JMurk** [comment]
Confirmed complete.
