### ISSUE TITLE
Utility Viewer - Galaxy Note - Compatibility test

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#198]
The City has recently made the move to Galaxy Note as the tablet; as such, some new issues are becoming apparent:

After logging into the DPW Application Portal and into any of the mobile applications an error message appears on the screen.  The error message reads “The device you are using does not support the use of this application.  You may experience unwanted functionality if you continue”.  

Please adjust the test of the device / resolution so that this message does not display for users of the Galaxy Note.

**Comment by taojun545** [comment]
I checked the code in the mobile applications, and the alert message will be shown when device type is "Phone". So Galaxy Note, iPhone and all other phones will show that message. 

I talked with Brendan, and in the short term, we can disable that message, but we need to do more testing on different devices with different OS in future.

**Comment by alanfoster99** [comment]
My apologies -- the device is actually a Galaxy Tab E

**Comment by taojun545** [comment]
If the device is tablet, the message should not be shown. I tested it on Samsung Galaxy Tab 4, and the message didn't pop up. Could you confirm what kind of device has that message pop-up?

**Comment by alanfoster99** [comment]
That was the model supplied to us this morning from the City distribution

**Comment by taojun545** [comment]
Thanks for your information. So when you opened Utility Viewer Mobile Application, the new device pop-up the message? http://dpwview.baltimorecity.gov/water/portal/index.aspx

**Comment by alanfoster99** [comment]
That is correct

**Comment by taojun545** [comment]
Thank you for your confirmation. OK,  I will disable the message for all the mobile applications.

**Comment by taojun545** [comment]
I have disabled pop-up alert message for all the mobile applications on dev. The apps are below;
- Utility Viewer (Mobile)
- SSO
- Leak
- PST
- Valve and Hydrant Status

**Comment by alanfoster99** [comment]
Unable to test -- will update when device is available.

**Comment by alanfoster99** [comment]
Closing
