### ISSUE TITLE
Utility Viewer - Galaxy Note - Geocoder

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#199]
The “locate” feature at the bottom of the screen does not work properly on the new Galaxy tablets.  It allows you to search for a specific address and finds it, but when you try to switch back to map view to see the address the map no longer appears. 

Please correct the functionality so that the map view persists.

**Comment by taojun545** [comment]
I fixed the issue on dev. Also I disabled the alert message which only applies to phone.

**Comment by taojun545** [comment]
The fix is only for Utility Viewer Mobile.

**Comment by alanfoster99** [comment]
Unable to test -- will update when device is available.

**Comment by taojun545** [comment]
As Stephen requested, I have pushed the fixes into production for both “Utility Viewer (Mobile)” and “Water Valve Status”. And he confirmed the fixes.

**Comment by alanfoster99** [comment]
Thanks!
