### ISSUE TITLE
Utility Viewer -  Water Tools - Date Formating

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#20]
Issue:  Across the various windows in the water tools, dates are displayed in different formats.

Resolution:  Please make all date fields display like this:
![image](https://f.cloud.github.com/assets/5805454/1887646/f770b6ae-7a00-11e3-954f-556782162696.png)

_Please make sure that the input/display boxes are large enough to display these formats.  Some may need to be enlarged_

**Comment by kanglu666** [comment]
all other date fields in the valve window will have date format: 05/15/2011 format. (change the layout may be mess up some others, so it's better just keep it as is.)

date fields in save plan window will have date format : January 14, 2014 format

**Comment by JMurk** [comment]
Update all to MM/DD/YYYY please.

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
It appears the Date Filters and the Created Date column on the Find Existing Plan window are still not the correct format.  Please update to MM/DD/YYYY.
![image](https://f.cloud.github.com/assets/5805454/1912035/cfc43b1c-7d34-11e3-93aa-76ff9e6b3058.png)

**Comment by JMurk** [comment]
Confirmed complete.
