### ISSUE TITLE
Utility Viewer - Plan Information - Enforce Required Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#21]
Issue - When saving a Valve Open/Close plan, the system does not require the user to enter Plan Name or Description.  The user should not be able to save the plan until both fields are populated.

Steps to Recreate:
1. Click the Update valve status button
2. Select Valves
3. Toggle the check box next to a few valves 
4. Click Initiate Plan

Resolution:  Please make Plan Name and Description required fields.  Make sure that there is a message OR red line under the fields when a user tries to save without populating them.

**Comment by JMurk** [comment]
Please make "Description" a required field as well.

**Comment by kanglu666** [comment]
red line under the description fields will show when this field is blank/empty.

**Comment by JMurk** [comment]
I tested this and tried to save the record.  It correctly did not save, however the save button became disabled and I was not able to edit the record and save again.  The save button should be disabled and there should probably be a notification when the user clicks save that the system is not saving the record because the description field is missing.
