### ISSUE TITLE
Utility Viewer -  Verify Wachs Data

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#22]
_As Per Amy's Comment_:  "Can someone check that the Wachs data updates are working daily?"

Please verify and respond here.

**Comment by gjmkelly** [comment]
Programmatically, Wachs data updates are working daily,  However, the [water].[water].[MAINT2WATER_VLV] table that is the basis for updating shows no last visit/operated dates after 10/10/2013.  So data is three months out of date.
