### ISSUE TITLE
Utility Viewer - Reverse Operations Plan - Naming

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#24]
Is is possible to programatically add "- Reverse Operation" to the end of a plan name for the reverse plan?  For example, in the figure below, the second record would be "joe - Reverse Operation"

![image](https://f.cloud.github.com/assets/5805454/1888948/37383132-7a14-11e3-81d8-ca81b33040f8.png)

Also, can we make it so that there can not be duplicate plan names? Does that make sense?

**Comment by JMurk** [comment]
It appears that when I try to save a duplicate plan name, a error is prompted that says "Please do Tracing Analysis first!!"  --  This should say "Plan name already exists!" for this error.

**Comment by kanglu666** [comment]
as i said before, it's a whole process to save a plan after doing the tracing. after the tracing, click the save button , the plan will be saved. 
if the plan window is still on, then if you click cancel or go the valve list tab do some changes, you need click the continue button, go the plan window, save an new plan.

**Comment by JMurk** [comment]
Completed.  Unique plan name has been deferred.
