### ISSUE TITLE
Utility Viewer -  Valves Plan - Details/Update Window - Changes

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#25]
Issue:  There are numerous changes that should be made to the valve plan details and update plan information windows.
1. Plan Name, Plan Type, and When to be Executed should be Non-editable.
2. Status should be editable (drop down values of Pending, In Progress, and Complete)
3. An editable field for Actual Start Date should be added above Date Completed and below When to be Executed.
4. Related Plan ID should be changed to show Related Plan Name instead

![image](https://f.cloud.github.com/assets/5805454/1889332/c7706328-7a19-11e3-98bf-dedca4a7cd6a.png)

Resolution:  Please make above updates, and make sure the following validation checks are in place before the user's edits are committed:
-If Status = Pending, Actual Start Date is Null
-If Status = In Progress, Actual Start Date is Not Null
-If Status = Complete, Date Completed is No Null

**Comment by JMurk** [comment]
Note:  This goes for the Plan Information page after click the Details button AND for the Plan information page after opening the plan from search results.

**Comment by JMurk** [comment]
This widow still has numerous outstanding issues in BOTH locations.

Valve Open/Close Plan Evaluation window:
1. Plan Name still allows users to input into the text box.  It should be non-editable.
2. Status should be editable with drop down values of Pending, In Progress, Complete.
3. Description is missing

Find Existing Plan - Existing Plan Information Window
1. Assigned is misspelled.
2. Status should be editable with drop down values of Pending, In Progress, Complete.
3. Description is missing.

Please make these updates on both screens.

**Comment by JMurk** [comment]
What is the status of these updates?

**Comment by kanglu666** [comment]
Plan Name and plan type are now non-editable.
"Assigned is misspelled":  fixed

**Comment by JMurk** [comment]
Closing.
