### ISSUE TITLE
Utility Viewer - New Data Feed

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#28]
I have created a new Map Service called UAMD_Water.  Please add this to the Utility Viewer under the UAMD feed as UAMD-Water.  Also, please rename the existing UAMD feed to UAMD-Wastewater.

The new UAMD-Water feed should only be shown in the WAView.

Let me know if you have any questions.

**Comment by kanglu666** [comment]
layer "UAMD Water" has been added into WAVIEW
UAMD layer in WWView has been rename to UAMD Wastewater

**Comment by JMurk** [comment]
Confirmed Completed
