### ISSUE TITLE
Utility Viewer -  Find Existing Plan - Created By Drop Down - Needs All Users Option

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#33]
Issue:  There is no way for a user to remove the Plan Created By search filter (if they are not sure who the creator was). 

![image](https://f.cloud.github.com/assets/5805454/1911969/c854c51e-7d33-11e3-88a9-40f3a8fc93cd.png)

Resolution:  Please add an "-All Users-" option to the Plan Created By drop down.  This should not put any filter on the Created By field.

**Comment by JMurk** [comment]
I do not see an -All Users- option for Plan Created By.

**Comment by JMurk** [comment]
What is the status of this update?

**Comment by kanglu666** [comment]
just don't chose any one in the drop down list, then it will show the default value '-All Users-'

**Comment by JMurk** [comment]
Closing.
