### ISSUE TITLE
Utility Viewer - Add New Data Feed to WWView

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#35]
Please add a new data feed called "Cityworks - Wastewater" to WWView.  It may be placed at the top of all layers.

The map service is published on the dev box dpw-gwdev01-srv and is called "Cityworks_Wastewater.

Let me know if you need any further info.

**Comment by kanglu666** [comment]
dpw-gwdev01-srv is not for outside, it will not work when adding it to the dashboard

**Comment by JMurk** [comment]
Ian, can we make dpw-gwdev01-srv accessible to the outside?

**Comment by JMurk** [comment]
Now in issue #49
