### ISSUE TITLE
Utility Viewer -  Water Tools - Viewer Permissions

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#36]
When a user's permissions is set to "Viewer" (or 1 in the table), does that mean that they have access to the valve status tool, but can not make any edits?  If not, what does this permission do?

**Comment by kanglu666** [comment]
Viewer means that they have access to the valve status tool, but can not make any edits

**Comment by JMurk** [comment]
Ok, great.  Thanks Lu.
