### ISSUE TITLE
Utility Viewer - valve Status Window - Valve Information

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#4]
Issue:  Is there any way to differentiate between the labels and the values?

![image](https://f.cloud.github.com/assets/5805454/1871801/e6a2a55a-789b-11e3-8c13-5f10833a6952.png)

Resolution:  Would it be possible to make the labels bold?

**Comment by JMurk** [comment]
Lu, was there any change made to this?

**Comment by kanglu666** [comment]
i cant change the style separately, because this part is generated by a HTML template which is consider as a whole part. So just keep it as is,

**Comment by JMurk** [comment]
Ok, it will stay as is.
