### ISSUE TITLE
Utility Viewer -  Investigate IE11 Compatibility Mode Issue

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#40]
Please investigate why the Utility Viewer will not load when compatibility mode is enabled for IE11.  

Resolve if possible.

**Comment by JMurk** [comment]
Any findings on this issue?

**Comment by kanglu666** [comment]
Utility Viewer now supports IE11 Compatibility Mode, Please Test

**Comment by JMurk** [comment]
Completed
