### ISSUE TITLE
Utility Viewer -  Export Function - Server Errors for a Few Layers

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#42]
Issue:  The following layers currently throw errors when attempting to export:

-Lateral Address Points
-Lateral Root Treatment
-Sewer Manhole
-Water Valves
-Water Services
-Active Water Mains
-Abandoned Water Mains
-Valve Condition

I believe that some of these are having issues because they have joined tables.  Some, however do not, so I am unsure of the issue there.

Resolution: Please investigate and resolve accordingly.

**Comment by JMurk** [comment]
Also getting an error for exporting data within the UAMD Water feed.  Those data sources are pgdb not SDE, however.

Lu,  Please investigate all of these layers.

**Comment by kanglu666** [comment]
just test the sewer manholes layer, it's working.
where is the UAMD water feed?

**Comment by JMurk** [comment]
WAView

**Comment by JMurk** [comment]
**Layers still throwing errors:**

Water

<ul><li>Water Valves</li>
<li>Water Services</li>
<li>Active Water Mains</li>
<li>Abandoned Water Mains</li>
<li>Valve Condition</li></ul>

WasteWater

<ul><li>Sewer House Connection</li>
<li>Lateral/CO Points</li></ul>

UAMD Water

<ul><li>Water Projects</li>
<li>Water Main Condition and Criticality</li></ul>

UAMD Wastewater

<ul><li>Lateral Address Points</li>
<li>Lateral Root Treatment</li></ul>

**Comment by kanglu666** [comment]
Export CSV function updated. 
i tested the Water Valves and Valve Condition layer, working fine.
Please test all other layers, let me know which layer will throw error.

**Comment by JMurk** [comment]
Still errors for the following layers:

-Lateral/CO Points
-Water Projects
-Water Main Condition and Criticality
-Lateral Address Points
-Lateral Root Treatment

**Comment by kanglu666** [comment]
All fixed. 
Lateral/CO Points data is huge, has 200,000 + records. the export CSV function will take several  mins to finish it. anyway, please test.

**Comment by JMurk** [comment]
Water Main Condition and Criticality is still not working.  All others have been fixed.

**Comment by kanglu666** [comment]
fixed, please test.

**Comment by JMurk** [comment]
Confirmed complete.
