### ISSUE TITLE
Utility Viewer - Repoint CCTV Function

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#43]
Issue:  Currently the CCTV function in the Utility Viewer is pointing at the CCTV_Reference table in the Wastewater geodatabase.  Recently, a 2-way replica was established for this same table in the Operations geodatabase.  We would like to re-point the Utility Viewer to the CCTV_Reference in the Operations geodatabase.  The purpose for doing this is so that CCTV Videos can be accessible as soon as they are added by UAMD staff (Dave).

Let me know if you need any more specific information.

**Comment by kanglu666** [comment]
Utility Viewer CCTV function has been repoint to the multi version view CCTV_Reference_VW in Operations database.

**Comment by JMurk** [comment]
Completed
