### ISSUE TITLE
Utility Viewer - RAP Confirmation Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#46]
Issue:  The text in the confirmation message has no capitalization.

![image](https://cloud.githubusercontent.com/assets/5805454/2741752/7a7928c6-c6f3-11e3-904f-7262b79acdf5.png)

Resolution:  Please update confirmation message to read:

"Problem report has been submitted"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
