### ISSUE TITLE
Utility Viewer - Add New Map Feeds

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#49]
Please add the following feeds to the Utility Viewer:
1. Work Orders (dpw-gwdev01-srv as Cityworks_Workorders) WWView, SWView, and WAView, above CSRs
2. SSO (use map service from application, 10.2).  WWView, above UAMD Wastewater
3. FSE (use map service from application) WWView, above UAMD Wastewater

**Comment by JMurk** [comment]
All feeds would be off by default.

**Comment by kanglu666** [comment]
done, please test

**Comment by JMurk** [comment]
Confirmed for FSE and SSO.  Waiting on Cityworks data to be ready.

**Comment by JMurk** [comment]
We may need a new SSO map service for the Utility Viewer.  Will get feedback form UAMD first.

**Comment by JMurk** [comment]
All layers now in UV.  Closing.
