### ISSUE TITLE
Utility Viewer - Scenario Plan Type & Adjust Permissions

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#50]
Please add a plan type of "Scenario" for all Main and Valve Shutdown plan options.

Also, users with Viewer permission should be able to save plans where Plan type = Scenario ONLY.  They should not be able to save Planned Shutdowns or Emergency Shutdowns.

![image](https://cloud.githubusercontent.com/assets/5805454/2843835/adb79a30-d083-11e3-842f-38c53196ea67.png)

**Comment by JMurk** [comment]
Needs to be discussed.

**Comment by JMurk** [comment]
Please Add a Plan Type of "Scenario"

**Comment by kanglu666** [comment]
Plan Type of "Scenario" has been added.

**Comment by JMurk** [comment]
Confirmed complete.
