### ISSUE TITLE
Utility Viewer - Highlight Features for Existing Plans

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#51]
Issue:  When a user opens and existing plan, the app zooms to the location, but does not highlight the features.

Steps to recreate:
1. Search for an existing plan using the Find Existing Plan tool
2. Highlight a plan from the results and click select to open it

Resolution:  Please update so the features are highlighted the same as when the trace was initially executed.

**Comment by kanglu666** [comment]
after trace, i will get the geometries for all features in that trace.
but for existing plan, we are get the attributes from the valve status and plan tables. no geometry attributes.
the only way to highlight them on the map is select one feature then i will call the map service get the geometry back based on ids. but one select just show one feature.

**Comment by JMurk** [comment]
Is there any way to have a button or something that they can re-run the original trace to get the symbology?  Lets talk about this.

**Comment by JMurk** [comment]
Please implement as per discussion in status meeting 5/8/24

**Comment by kanglu666** [comment]
an new button call "Highlight" has been added at the bottom of the "Existing Plan Information" form.
after select an plan go to the plan information tab, you will see the button.
click the button, map will highlight the plan.

**Comment by JMurk** [comment]
Great! --Confirmed complete.
