### ISSUE TITLE
Utility Viewer - Existing Plan Information - Replace TAGs with IDs

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#52]
Issue:  On the Existing plan information window, the Valve and Main TAGs are displayed.  

Resolution:  Please update to display Valve ID (VLV_ID) for valves and Main ID (MAIN_ID) for mains.

![image](https://cloud.githubusercontent.com/assets/5805454/2844126/cd2019da-d086-11e3-9bff-f64827f82fca.png)

![image](https://cloud.githubusercontent.com/assets/5805454/2844132/e2b75772-d086-11e3-8d49-4190b59d429c.png)

**Comment by JMurk** [comment]
Also, please make Pipe Size  on the Mains w/o service screen an integer.  All the trailing 0's are unnecessary. Do the same for Lat Size on the Hydrant w/o service page as well:

![image](https://cloud.githubusercontent.com/assets/5805454/2844291/ecc7e1c6-d088-11e3-8445-2751a90e35f9.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
