### ISSUE TITLE
Utility Viewer - Map Layers - Active Leaks

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#53]
Please add the Current Leaks as a feed to the Utility Viewer.  These are the current leaks as created by the Leak Detection App.  The user will need to be able to access the Leak Report, dynamically generated and accessed via the "Select Leaks" tool -> "Report" button at the bottom.

**Comment by kanglu666** [comment]
which views do you want to add the the "New" leak layer into? and what name should give to the new leak layer?  right now, the old leak layer has name "Leak", and the select Leak tool is based on the layer name.

**Comment by alanfoster99** [comment]
best to ask Joe -- assigning to him

**Comment by JMurk** [comment]
Lu,  can we just add the new leaks to the existing map service?

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
