### ISSUE TITLE
Utility Viewer - Add Fields to Update Valve Status Window

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#55]
Please add access and problem fields to the Update Valve Status window as editable.  They are stored in the VALVE_STATUS table as VALVE_ACCESS and VALVE_PROBLEM. Both are varchar 255.

**Comment by JMurk** [comment]
Lu, what is the status of this change?

**Comment by kanglu666** [comment]
VALVE_ACCESS and VALVE_PROBLEM fields have been added into the UV valve status screen as editable for user updating values in db (valve_status table.)

**Comment by JMurk** [comment]
Confirmed complete.
