### ISSUE TITLE
Utility Viewer - Link SSO, FSE, and New Leaks to Reports

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#56]
When a user identifies SSOs, FSEs, or New leaks, the report button at the bottom of the Results Display panel should launch the report in a new tab.  SSO will launch be the most recent report.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed for FSE.  

Lu- Can you launch the report for all SSO layers?

Alan- Can you confirm for Leaks?  Are there any new leaks in there yet?

**Comment by kanglu666** [comment]
SSO report is only for 24 hour and 5 day

**Comment by JMurk** [comment]
Fair enough.  Alan- please confirm leaks and close.

**Comment by alanfoster99** [comment]
Confirmed for leaks and closing.
