### ISSUE TITLE
Utility Viewer - Discrepancies - Confirmation Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#59]
Issue:  Please fix the typo in the confirmation message after creating a discrepancy point (discrepancy, not aiscrepacny)

![image](https://cloud.githubusercontent.com/assets/5805454/3104883/e24eeb28-e66c-11e3-8f48-cf9428b84578.png)

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
