### ISSUE TITLE
Utility Viewer - Discrepancies - Required Feilds

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#62]
Issue:  The system allows a discrepancy to be saved without any information added to the form.

Resolution:  Please make all fields required with the EXCEPTION of source.

**Comment by kanglu666** [comment]
all fields are required now, alert message will pop up if there are blank value in the fields

**Comment by JMurk** [comment]
Please make make Source not required and change the message to "Warning: All fields required, except Source" - per our conversation

**Comment by kanglu666** [comment]
done, please clear cache and test

**Comment by JMurk** [comment]
Confirmed complete.
