### ISSUE TITLE
Utility Viewer - Discrepancies - Add to Mobile

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#63]
Please add the discrepancy reporting functionality to Utility Viewer mobile ASAP.

**Comment by kanglu666** [comment]
adding discrepancy tool has been plugged into the utility viewer mobile app.
please clear browser cache and test.

**Comment by JMurk** [comment]
Confirmed complete.... please be sure bug fixes to mobile discrepancy tool get pushed to all locations.
