### ISSUE TITLE
Utility Viewer - Mobile Discrepancies - Update Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#64]
Please update the following pop-up message to read:  "Add New Discrepancy? - Tap on Map!"

-Be sure that Discrepancy is spelled correctly.  
-Make the change in the Leak Detection App as well

![image](https://cloud.githubusercontent.com/assets/5805454/3134840/c2b15a0c-e82a-11e3-8ddb-c10c93b94c39.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
