### ISSUE TITLE
Utility Viewer -  Mobile Discrepancies - Change Warning Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#65]
Please update the following warning message to read:

"Cannot Add New Discrepancy.  Please Zoom In to the Location First!"

![image](https://cloud.githubusercontent.com/assets/5805454/3134981/c95f0e60-e82c-11e3-835f-b4e662632bc3.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
