### ISSUE TITLE
Utility Viewer - Mobile Discrepancies - Fields Blank by Default

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#66]
Issue:  After creating a new discrepancy point, the system populates the top 3 columns with default values.  These should be kept blank by default.
![image](https://cloud.githubusercontent.com/assets/5805454/3135011/32ff136a-e82d-11e3-912b-880d2e89b306.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
