### ISSUE TITLE
Utility Viewer - Mobile - Change Web Page Title

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#69]
Please change the title of the web page so that browser tabs read "Baltimore City Utility Viewer - Mobile."  

Also please reference the same .ico file that the desktop UV uses (see HTML below)

![image](https://cloud.githubusercontent.com/assets/5805454/3135111/6d27360c-e82e-11e3-8c2e-82055a6d747c.png)

link rel="shortcut icon" href="resources/icons/BaltCity.ico"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
