### ISSUE TITLE
Utility Viewer - Main Trace - Zoom To Button for Plan Features

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#75]
Add a button that will allow users to zoom to a selected feature within the Plan Information window.

![image](https://cloud.githubusercontent.com/assets/5805454/3513464/01ba8b40-06c3-11e4-87bb-83ce8e577a51.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
