### ISSUE TITLE
Utility Viewer - Main Trace - Spawn Valve Status Window from Plan Information

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#77]
Add the ability to spawn the valve status window from the plan information window.  The valve status window should load all selected valves within the plan information window.

![image](https://cloud.githubusercontent.com/assets/5805454/3513790/372ff974-06c6-11e4-8a20-8e2b32f7ea78.png)

**Comment by kanglu666** [comment]
done, please test

**Comment by JMurk** [comment]
Confirmed complete.
