### ISSUE TITLE
Utility Viewer - Plan Information - Add and Remove Columns

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#78]
Add columns of Elevation and Max Turns to the valves tab of the plan information window.  Also, remove Assigned and Execute Date.

![image](https://cloud.githubusercontent.com/assets/5805454/3514002/4fa21a58-06c8-11e4-9001-a21389f498ce.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Can you cut down the number of decimal places in Max Turns to 2?

![image](https://cloud.githubusercontent.com/assets/5805454/3738256/c0a8e07a-173e-11e4-9039-50539f68a7f8.png)

**Comment by kanglu666** [comment]
updated for prod UV.please test

will update on dev once Ian copy the "water" database in.

**Comment by kanglu666** [comment]
also updated for dev UV. please test

**Comment by JMurk** [comment]
Confirmed complete in both environments.
