### ISSUE TITLE
Utility Viewer - Valve Information - Reorder Position Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#79]
Please reorder fields in the Position section within the Valve Status window.  Make Position Left second and Position Found first.

![image](https://cloud.githubusercontent.com/assets/5805454/3514541/ec5b8510-06cc-11e4-86df-a60a08ef647d.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
