### ISSUE TITLE
Utility Viewer - New View - Water Operations

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#81]
Per Amy:

MAKE A “WATER OPERATIONS” TOP LEVEL GROUP TO INCLUDE HYDRANT STATUS, VALVE CONDITION (TAKE FROM WATER), WATERMAIN SHUTDOWN PLANS, PRIVATE HYDRANTS, …(NEW COMMENT)
Also need a layer that highlights valves that are closed

**Comment by JMurk** [comment]
Map Service Water_Operations has been published on dpw-gw03-srv.  

Lu-  Please add a feed to the Utility Viewer titled "Water Operations."  It should only be in WAView.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
