### ISSUE TITLE
Utility Viewer - Identify Tool Enhancement

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#83]
Update the identify tool so that it automatically identifies all visible layers without having to select layers from the drop down.

**Comment by kanglu666** [comment]
Check with Amy

**Comment by JMurk** [comment]
Per Amy's response, can we exclude features that are not visible due to scale dependency?  This should only occur for the identify tool.

**Comment by JMurk** [comment]
I believe this functionality exists within the Activity Manager.  Can we push this to the Utility Viewer?

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
It looks like this is not including layers from the BaseMap.  Could you make sure that those are inclued.

It also appears that this was pushed to prod because the "Feature Information" window is not available there.

**Comment by JMurk** [comment]
Looks good in prod, can you make the changes in dev as well?

**Comment by jday3** [comment]
yup, its in dev now

**Comment by JMurk** [comment]
Confirmed complete.
