### ISSUE TITLE
Utility Viewer -  Work Order Symbology Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#84]
Separate the work orders by water, sewer, storm, hydrants, meter shop, etc. – some logical groups and then could only display the appropriate group within each view.

**Comment by JMurk** [comment]
Created New Map services for Work Orders.  Please add them as feeds to the corresponding Views in the Utility Viewer.

-Sewer_WorkOrders || "Sewer Work Orders" || WWView
-Storm_WorkOrders || "Stormwater Work Orders" || SWView
-SurfaceRepair_WorkOrders || "Surface Repair Work Orders" ||  WAView, SWView, WAView
-Water_WorkOrders || "Water Work Orders" || WAView

The should be placed toward the top of all layers within the view.

Once these are in, you can remove the Existing Work Orders feed.

**Comment by kanglu666** [comment]
done on both dev and prod, please test

**Comment by JMurk** [comment]
Confirmed complete in prod.
