### ISSUE TITLE
Utility Viewer - Valve Status- Last Edit User

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#85]
Please populate the VALVE_STATU.last_edited_by with the user name of the last editor in the Utility Viewer.

This field should also be exposed as a non-editable field in the Valve Status window.  Label as "Last Editor" and place above the Position group.

![image](https://cloud.githubusercontent.com/assets/5805454/3605488/dd2298a8-0d2b-11e4-9de4-e17003f93866.png)

**Comment by kanglu666** [comment]
updated. please test the prod UV.

**Comment by JMurk** [comment]
Confirmed complete.
