### ISSUE TITLE
Utility Viewer - Reformat the Active Legend Output

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#87]
Re design the active legend output so that it appears as a "professional looking" legend.

Developers:  Is it possible to export with styling (e.g. borders, headers, ect.)?

**Comment by jday3** [comment]
Yeah, have control over the html/css output. It would be useful to have a mockup of how it should look ideally.

**Comment by JMurk** [comment]
Here is a very quick mock-up.  Does this help?

![image](https://cloud.githubusercontent.com/assets/5805454/5666695/81b45e5a-972f-11e4-8d8b-381e017a1d3e.png)

**Comment by jday3** [comment]
Yeah that helps

**Comment by jday3** [comment]
Done on dev.

**Comment by jday3** [comment]
I threw it on production as well since it wont break anything. Let me know if there are any adjustments you think I should make - it is pretty simple to update

**Comment by JMurk** [comment]
Looks pretty good... A couple things:
1. The headers have no spaces.  Can that be changed?
   ![image](https://cloud.githubusercontent.com/assets/5805454/5779113/213356e0-9d6e-11e4-8cf8-5aa7abc75d7a.png)
2. "Map Legend" should be in a larger font than anything else.
3. Can you change "(Active Legend)" to (Active Layers)"?

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
