### ISSUE TITLE
Utility Viewer - Mobile - Identify Functionality 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#92]
Add the ability to identify ALL features in the map.  The results should be the visible attributes of the selected feature.

**Comment by jday3** [comment]
Done, on dev. Any layer that is visible on the map is queried and clicking on a result will show all of the attributes of that particular feature in a separate window

**Comment by JMurk** [comment]
I like it.  Can will remove results from the BaseMap, Plats and Orthos layer?  Also, the "X" close button on the results window doesn't seem to be working.

**Comment by jday3** [comment]
I removed those 3 layers from results and fixed the close button, on dev

**Comment by JMurk** [comment]
Confirmed complete.  Please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
