### ISSUE TITLE
Utility Viewer - Add Time to Execute Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#95]
Please add time to the "When to be Executed" field in the shutdown plan information window.

![image](https://cloud.githubusercontent.com/assets/5805454/3755219/abe1a2c8-1822-11e4-9adb-f10afa23e104.png)

**Comment by kanglu666** [comment]
"When to be Executed" field has add time function now. please test in dev

**Comment by JMurk** [comment]
If possible, please format the time picker in am/pm.  If not, remove the seconds picker.

**Comment by kanglu666** [comment]
time picker has been added for the "When to be executed" field in PROD.
I will double check if we can change the time format or can remove the seconds picker.

**Comment by JMurk** [comment]
Please add the time function to "When to Reverse Operations" Field.

**Comment by kanglu666** [comment]
time picker has been added into "When to Reverse Operations" Field, please test in city dev
