### ISSUE TITLE
Utility Viewer - Add Planned Completion Time

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#96]
Please add a read-only field labeled "When to be Completed" to the plan information window.  

-This should NOT display for reverse plans
-This should be derived from the related plan (When to be executed date of the reverse plan.
-It should be placed directly below the "When to be Executed" field in the window

![image](https://cloud.githubusercontent.com/assets/5805454/3755302/6f0b45ba-1823-11e4-8525-f74232f6e6ee.png)

**Comment by kanglu666** [comment]
"When to be Completed" filed has been added in the existing plan form with including all the requirements above, please test in city dev

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated in PROD, ready for testing

**Comment by JMurk** [comment]
Confirmed complete.
