### ISSUE TITLE
Add user to "Assigned Employee" in Shutdown plan

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#97]
Please add the user CHAD FUHRMAN to the list of users that can be assigned a main shutdown plan.

Screen: Main Shutdown Plan Evaluation
Tab: Plan Information
Field: Assigned Employee

**Comment by kanglu666** [comment]
updated, please test

**Comment by DaveThomKCI** [comment]
completed.  Thanks Lu.
