### ISSUE TITLE
Utility Viewer - Valve Status - Save Confirmation Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#99]
Issue: After updating the valve status and clicking save, they system prompts a message that says the information was saved. This message disappears after a couple seconds, not requiring the user to click OK.

Resolution: Please investigate and resolve accordingly.  The user should have to click OK to close the message modal screen.

**Comment by kanglu666** [comment]
fixed at city dev, please test

**Comment by JMurk** [comment]
Confirmed complete on dev.  Ready for Prod.

**Comment by kanglu666** [comment]
ready for testing in prod

**Comment by JMurk** [comment]
Confirmed complete.
